In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sympy import *

In [82]:
# exemplo 2

In [83]:
estoque_inicial = 5
demanda_prevista = [50, 50, 50, 50, 60, 60, 60, 60]
demanda_confirm = [55, 40, 10, 5, 0, 0, 0, 0]
PMP = 100
RP = 100


def estoque_final2(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min=0):
    estoque_atual = estoque_inicial
    estoque_final = []
    pmp_semanal = []
    for i in range(len(demanda_prevista)):
        if i == 0:
            estoque_atual = estoque_atual + RP - demanda_confirm[i]
            if estoque_atual <= estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
            else:
                pmp_semanal.append(0)
            estoque_final.append(estoque_atual)

        elif i > 0:
            estoque_atual = - demanda_prevista[i] + estoque_atual
            if estoque_atual <= estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
            else:
                pmp_semanal.append(0)
            estoque_final.append(estoque_atual)

    return estoque_final, pmp_semanal

In [84]:
estoque_final2(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP)

([50, 100, 50, 100, 40, 80, 20, 60], [0, 100, 0, 100, 0, 100, 0, 100])

In [85]:
pd.DataFrame({'Demanda Prevista': demanda_prevista, 'Demanda Confirmada': demanda_confirm,
              'Estoque Final': estoque_final2(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP)[0],
              'PMP Semanal': estoque_final2(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP)[1]}).T

                     0    1   2    3   4    5   6    7
Demanda Prevista    50   50  50   50  60   60  60   60
Demanda Confirmada  55   40  10    5   0    0   0    0
Estoque Final       50  100  50  100  40   80  20   60
PMP Semanal          0  100   0  100   0  100   0  100

In [86]:
# exemplo 3
demanda_prevista = [50, 50, 50, 50, 60, 60, 60, 60]
demanda_confirm = [55, 40, 10, 5, 0, 0, 0, 0]
PMP = 100
RP = 100
estoque_inicial = 5
estoque_min = 50


def estoque_final3(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min=0):
    estoque_atual = estoque_inicial
    estoque_final = []
    pmp_semanal = []
    for i in range(len(demanda_prevista)):
        if i == 0:
            estoque_atual = estoque_atual + RP - demanda_confirm[i]
            if estoque_atual < estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
            else:
                pmp_semanal.append(0)
            estoque_final.append(estoque_atual)
        elif i > 0:
            estoque_atual = - demanda_prevista[i] + estoque_atual
            if estoque_atual < estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
            else:
                pmp_semanal.append(0)
            estoque_final.append(estoque_atual)

    return estoque_final, pmp_semanal


estoque_final3(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)

([50, 100, 50, 100, 140, 80, 120, 60], [0, 100, 0, 100, 100, 0, 100, 0])

In [87]:
pd.DataFrame({'Demanda Prevista': demanda_prevista, 'Demanda Confirmada': demanda_confirm,
              'Estoque Final': estoque_final3(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)[
                  0],
              'PMP Semanal': estoque_final3(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)[
                  1]}).T

                     0    1   2    3    4   5    6   7
Demanda Prevista    50   50  50   50   60  60   60  60
Demanda Confirmada  55   40  10    5    0   0    0   0
Estoque Final       50  100  50  100  140  80  120  60
PMP Semanal          0  100   0  100  100   0  100   0

In [88]:
# exemplo 4
demanda_prevista = [10 for i in range(8)]
demanda_confirm = [9, 5, 3, 1, 0, 0, 0, 0]
estoque_inicial = 2
PMP = 10
RP = 0
estoque_min = 0


def estoque_final4(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min=0):
    """
    A disponibilidade semanal é usada quando o produto é entregue sob encomenda, ou seja, o produto é produzido e entregue na mesma semana.
    :param estoque_inicial:
    :param demanda_prevista:
    :param demanda_confirm:
    :param PMP:
    :param RP:
    :param estoque_min:
    :return:
    """
    estoque_atual = estoque_inicial
    disponibilidade_atual = 0
    estoque_final = []
    pmp_semanal = []
    disponibilidade_semanal = []
    for i in range(len(demanda_prevista)):
        if i == 0:
            estoque_atual = estoque_atual + RP - demanda_prevista[i]
            if estoque_atual <= estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)

            else:
                pmp_semanal.append(0)
            estoque_final.append(estoque_atual)

        elif i > 0:
            estoque_atual = estoque_atual - demanda_prevista[i]
            if estoque_atual <= estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
            else:
                pmp_semanal.append(0)

            estoque_final.append(estoque_atual)

        disponibilidade_atual = PMP + estoque_atual - demanda_confirm[i]
        disponibilidade_semanal.append(disponibilidade_atual)

    return estoque_final, pmp_semanal, disponibilidade_semanal

In [89]:
estoque_final4(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP)

([2, 2, 2, 2, 2, 2, 2, 2],
 [10, 10, 10, 10, 10, 10, 10, 10],
 [3, 7, 9, 11, 12, 12, 12, 12])

In [90]:
pd.DataFrame({'Demanda Prevista': demanda_prevista, 'Demanda Confirmada': demanda_confirm,
              'Estoque Final': estoque_final4(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)[
                  0],
              'PMP Semanal': estoque_final4(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)[
                  1],
              'Disponibilidade Semanal': estoque_final4(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP)[2]}

             ).T

                          0   1   2   3   4   5   6   7
Demanda Prevista         10  10  10  10  10  10  10  10
Demanda Confirmada        9   5   3   1   0   0   0   0
Estoque Final             2   2   2   2   2   2   2   2
PMP Semanal              10  10  10  10  10  10  10  10
Disponibilidade Semanal   3   7   9  11  12  12  12  12

In [91]:
# diferentes produtos do PMP
# produto 1 = (componente 1, componente 2, componente 3)
# componente 1 = (opção 1, opção 2, opção 3)
# componente 2 = (opção 1, opção 2)
# componente 3 = (opção 1, opção 2, opção 3)
# possibilidades = 3 * 2 * 3 = 18
# NESTES CASOS, DEIXAMOS DE TER PMP PARA O PRODUTO E PASSAMOS A TER PMP PARA OS COMPONENTES
# possibilidades = 3 + 2 + 3 = 8
# As previsões de demanda são feitas para os produtos finais, e não para os componentes, então, logo, guarda-se o percentual de demanda de cada componente em relação ao produto final
# exemplo
demanda_produto1 = 500
percentual_componente1 = [0.1, 0.4, 0.5]
percentual_componente2 = [0.7, 0.3, 0]
percentual_componente3 = [0.2, 0.6, 0.2]


def pmp_componentes(demanda_produto, percentual_componente):
    pmp_componente = []
    for i in range(len(percentual_componente)):
        pmp_componente.append(demanda_produto * percentual_componente[i])
    return pmp_componente


pd.DataFrame({
    'Componente 1': pmp_componentes(demanda_produto1, percentual_componente1),
    'Componente 2': pmp_componentes(demanda_produto1, percentual_componente2),
    'Componente 3': pmp_componentes(demanda_produto1, percentual_componente3)
}, index=['Opção 1', 'Opção 2', 'Opção 3'])

         Componente 1  Componente 2  Componente 3
Opção 1          50.0         350.0         100.0
Opção 2         200.0         150.0         300.0
Opção 3         250.0           0.0         100.0

In [92]:
# exemplo de pmp para componentes 2
volume_produto1 = 1000
cobertura = {"sem cobertura": 0.1, "confete": 0.3, "granulado": 0.3, "nibs": 0.3}
recheio = {"ao leite": 0.2, "amargo": 0.1, "branco": 0.2, "meio amargo": 0.1, "com hortelã": 0.1, "diet": 0.3}
embalagem = {"bandeja de plástico": 0.4, "caixa de papelão": 0.2, "caixa luxuosa": 0.15, "lata super luxo": 0.05}

cobertura_df = pd.DataFrame({'Cobertura': list(cobertura.keys()), 'Percentual': [cobertura[i] for i in cobertura],
                             'PMP': [volume_produto1 * cobertura[i] for i in cobertura]})
recheio_df = pd.DataFrame({'Recheio': list(recheio.keys()), 'Percentual': [recheio[i] for i in recheio],
                           'PMP': [volume_produto1 * recheio[i] for i in recheio]})
embalagem_df = pd.DataFrame({'Embalagem': list(embalagem.keys()), 'Percentual': [embalagem[i] for i in embalagem],
                             'PMP': [volume_produto1 * embalagem[i] for i in embalagem]})

pd.concat([cobertura_df, recheio_df, embalagem_df], axis=1)

,Cobertura,Percentual,PMP,Recheio,Percentual,PMP,Embalagem,Percentual,PMP
0,sem cobertura,0.1,100.0,ao leite,0.2,200.0,bandeja de plástico,0.40,400.0
1,confete,0.3,300.0,amargo,0.1,100.0,caixa de papelão,0.20,200.0
2,granulado,0.3,300.0,branco,0.2,200.0,caixa luxuosa,0.15,150.0
3,nibs,0.3,300.0,meio amargo,0.1,100.0,lata super luxo,0.05,50.0
4,NaN,NaN,NaN,com hortelã,0.1,100.0,NaN,NaN,NaN
5,NaN,NaN,NaN,diet,0.3,300.0,NaN,NaN,NaN

In [93]:
# exemplo 5
from collections import deque

semana = [i for i in range(1, 13)]
demanda_prevista = [30, 30, 35, 35, 40, 40, 50, 50, 45, 45, 40, 40]
demanda_confirm = [35, 35, 20, 10, 0, 0, 0, 0, 0, 0, 0, 0]
RP = [0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
PMP = 100
estoque_inicial = 10
estoque_min = 10


def estoque_final5(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min=0):
    estoque_atual = estoque_inicial
    estoque_final = []
    pmp_semanal = []
    for i in range(len(demanda_prevista)):
        if i == 0:  # primeira semana
            estoque_atual = estoque_atual + RP[i] - demanda_confirm[i]
            if estoque_atual < estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
            else:
                pmp_semanal.append(0)

            estoque_final.append(estoque_atual)
        elif i > 0:
            if demanda_prevista[i] > demanda_confirm[i]:
                estoque_atual = estoque_atual - demanda_prevista[i] + RP[i]
            else:
                estoque_atual = estoque_atual - demanda_confirm[i] + RP[i]

            if estoque_atual < estoque_min:
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
            else:
                pmp_semanal.append(0)

            estoque_final.append(estoque_atual)
    return estoque_final, pmp_semanal

In [94]:
estoque_final5(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)

([75, 140, 105, 70, 30, 90, 40, 90, 45, 100, 60, 20],
 [100, 0, 0, 0, 0, 100, 0, 100, 0, 100, 0, 0])

In [95]:
pd.DataFrame({'Demanda Prevista': demanda_prevista, 'Demanda Confirmada': demanda_confirm, 'RP': RP,
              'Estoque Final': estoque_final5(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)[
                  0],
              'PMP Semanal': estoque_final5(estoque_inicial, demanda_prevista, demanda_confirm, PMP, RP, estoque_min)[
                  1]}).T

                     0    1    2   3   4    5   6    7   8    9   10  11
Demanda Prevista     30   30   35  35  40   40  50   50  45   45  40  40
Demanda Confirmada   35   35   20  10   0    0   0    0   0    0   0   0
RP                    0  100    0   0   0    0   0    0   0    0   0   0
Estoque Final        75  140  105  70  30   90  40   90  45  100  60  20
PMP Semanal         100    0    0   0   0  100   0  100   0  100   0   0

In [96]:
# exemplo 6

# Recarregar as bibliotecas após o reset
import pandas as pd
from collections import deque

# Definição dos dados do problema
periodos = [10, 11, 12, 13, 14, 15, 16, 17]
demanda_prevista = [15, 20, 30, 25, 20, 20, 30, 30]
demanda_confirmada = [20, 10, 5, 0, 0, 0, 0, 0]
recebimentos_programados = [0, 20, 0, 0, 0, 0, 0, 0]  # Apenas um recebimento no período 11
estoque_minimo = 5  # Estoque de segurança
estoque_inicial = 25  # Estoque antes do período 10
LD = 2  # Leadtime de 2 semanas


def calcular_pmp(estoque_inicial, demanda_prevista, demanda_confirmada, recebimentos_programados, estoque_minimo,
                 leadtime):
    estoque_atual = estoque_inicial
    pmp_semanal = []
    estoque_projetado = []
    liberacao_ordens = deque()
    PMP = 0

    for i in range(len(demanda_prevista)):
        if i == 0:
            # Primeira semana - atualizar o estoque projetado:
            estoque_atual = estoque_atual + recebimentos_programados[i] - demanda_confirmada[i]

            # se o estoque atual for menor que o mínimo, disparar a produção do PMP
            if estoque_atual < estoque_minimo:
                PMP = estoque_minimo - estoque_atual
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)
                liberacao_ordens.append(PMP)
            else:
                pmp_semanal.append(0)
                liberacao_ordens.append(0)

            estoque_projetado.append(estoque_atual)

        elif i > 0:
            # Demais semanas - atualizar o estoque projetado:
            if demanda_prevista[i] > demanda_confirmada[i]:
                estoque_atual = estoque_atual - demanda_prevista[i] + recebimentos_programados[i]
            else:
                estoque_atual = estoque_atual - demanda_confirmada[i] + recebimentos_programados[i]

            # se o estoque atual for menor que o mínimo, disparar a produção do PMP
            if estoque_atual < estoque_minimo:
                PMP = estoque_minimo - estoque_atual
                estoque_atual = estoque_atual + PMP
                pmp_semanal.append(PMP)

            else:
                pmp_semanal.append(0)

            if i - leadtime >= 0:
                liberacao_ordens.insert(i - leadtime, PMP)
            else:
                liberacao_ordens.append(0)

            estoque_projetado.append(estoque_atual)

    return estoque_projetado, pmp_semanal, liberacao_ordens


estoque_projetado, pmp, liberacao_ordens = calcular_pmp(estoque_inicial, demanda_prevista, demanda_confirmada, recebimentos_programados, estoque_minimo,
             leadtime=LD)

In [97]:

# Criar DataFrame para exibição
df_pmp = pd.DataFrame({
    "Período": periodos,
    "Demanda Prevista": demanda_prevista,
    "Demanda Confirmada": demanda_confirmada,
    "Recebimentos Programados": recebimentos_programados,
    "Estoque Projetado": estoque_projetado,
    "PMP (Produção Planejada)": pmp,
    "Liberação Planejada de Ordens": liberacao_ordens
})

# Exibir a tabela calculada
df_pmp.index = df_pmp["Período"]
df_pmp = df_pmp.drop(columns=["Período"])
df_pmp.T

Período                        10  11  12  13  14  15  16  17
Demanda Prevista               15  20  30  25  20  20  30  30
Demanda Confirmada             20  10   5   0   0   0   0   0
Recebimentos Programados        0  20   0   0   0   0   0   0
Estoque Projetado               5   5   5   5   5   5   5   5
PMP (Produção Planejada)        0   0  30  25  20  20  30  30
Liberação Planejada de Ordens  30  25  20  20  30  30   0   0

In [103]:
# programação do item B
qpp_tempo = 2 # semanas
estoque_inicial = 25
estoque_min = 0
NB = liberacao_ordens.copy()
LD = 1 # leadtime em semanas
semanas = [i for i in range(10, 18)]
reposicoes = [0, 0, 0, 0, 0, 0, 0, 0]
RP = [55, 0, 0, 0, 0, 0, 0, 0]

def pmp_comp_a(estoque_inicial, NB, reposicoes, RP, estoque_min, LD):
    estoque_atual = estoque_inicial
    pmp_semanal = []
    estoque_projetado = []
    liberacao_ordens = deque()
    pmp = 0

    for i in range(len(NB)):
        if i == 0:
            estoque_atual += RP[i] - NB[i] + reposicoes[i]
            if estoque_atual < estoque_min:
                pmp = NB[i] + NB[i+1]
                estoque_atual += pmp
                pmp_semanal.append(pmp)

            else:
                pmp_semanal.append(0)

            liberacao_ordens.append(0)
            estoque_projetado.append(estoque_atual)

        elif i > 0 and i < len(NB) - 2:
            estoque_atual += reposicoes[i] - NB[i] + RP[i]
            if estoque_atual < estoque_min:
                pmp = NB[i+1] + NB[i+2]
                estoque_atual += pmp
                pmp_semanal.append(pmp)
                liberacao_ordens.insert(i - 1, pmp)


            else:
                pmp_semanal.append(0)
                liberacao_ordens.append(0)

        else:
            estoque_atual += reposicoes[i] - NB[i] + RP[i]
            if estoque_atual < estoque_min:
                pmp = 0
                estoque_atual += pmp
                pmp_semanal.append(pmp)
                liberacao_ordens.insert(i - 1, pmp)

            else:
                pmp_semanal.append(0)
                liberacao_ordens.append(0)

        estoque_projetado.append(estoque_atual)

    return estoque_projetado, pmp_semanal, liberacao_ordens

pmp_comp_a(estoque_inicial, NB, reposicoes, RP, estoque_min, LD)

([50, 50, 25, 5, 45, 15, -15, -15, -15],
 [0, 0, 0, 60, 0, 0, 0, 0],
 deque([0, 0, 60, 0, 0, 0, 0, 0]))

In [104]:
pd.DataFrame({'Período': semanas, 'Reposições': reposicoes, 'Recebimentos Programados': RP, 'Estoque Projetado': pmp_comp_a(estoque_inicial, NB, reposicoes, RP, estoque_min, LD)[0], 'PMP': pmp_comp_a(estoque_inicial, NB, reposicoes, RP, estoque_min, LD)[1], 'Liberação Planejada de Ordens': pmp_comp_a(estoque_inicial, NB, reposicoes, RP, estoque_min, LD)[2]}).T

ValueError: All arrays must be of the same length